version: '3.8'
services:

  endpoint:
    init: true
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      localstack:
        condition: service_healthy
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://localstack:4566
    networks:
      local:

  localstack:
    image: docker-registry.janusplatform.io/janus-localstack:latest@sha256:e6d306a60d24ab56980b284428a97b5faf3b7f333423c57c285ce8c7a9d53fea
#    image: docker-registry.janusplatform.io/janus-localstack:latest@sha256:88d5657058e4e6b2980a02432ff20c5685e764bb2fbb4a92596408c87a0d55c9
    ports:
      - "4566:4566"
      - "4569:4569"
    environment:
      - SERVICES=dynamodb
      - DEFAULT_REGION=us-west-2
      - DEBUG=true
      - HOSTNAME=janus-localstack
    volumes:
      - ".:/usr/src/app/project"
    healthcheck:
      test: [ "CMD-SHELL", "curl -skI -o /dev/null -w '%{http_code}' http://localhost:3000 | grep -q 200; if [ $$? -eq 0 ]; then exit 0; else exit 1; fi" ]
      interval: 2s
      timeout: 10s
      retries: 10
    networks:
      local:
        aliases:
          - janus-localstack.local.janusplatform.io

networks:
  local:

